function getSeriesData()
{
  return {
    "Bob's Burgers": {
    seasons: {
      "1": {
        "1": { title: "Human Flesh", tags: [] },
        "2": { title: "Crawl Space", tags: [] },
        "3": { title: "Sacred Cow", tags: [] },
        "4": { title: "Sexy Dance Fighting", tags: [] },
        "5": { title: "Hamburger Dinner Theater", tags: [] },
        "6": { title: "Sheesh! Cab, Bob?", tags: [] },
        "7": { title: "Bed & Breakfast", tags: [] },
        "8": { title: "Art Crawl", tags: [] },
        "9": { title: "Spaghetti Western and Meatballs", tags: [] },
        "10": { title: "Burger War", tags: [] },
        "11": { title: "Weekend at Mort's", tags: [] },
        "12": { title: "Lobsterfest", tags: [] },
        "13": { title: "Torpedo", tags: [] },
      },
      "2": {
        "1": { title: "The Belchies", tags: [] },
        "2": { title: "Bob Day Afternoon", tags: [] },
        "3": { title: "Synchronized Swimming", tags: [] },
        "4": { title: "Burgerboss", tags: [] },
        "5": { title: "Food Truckin'", tags: [] },
        "6": { title: "Dr. Yap", tags: [] },
        "7": { title: "Moody Foodie", tags: [] },
        "8": { title: "Bad Tina", tags: [] },
        "9": { title: "Beefsquatch", tags: [] },
      },
      "3": {
        "1": { title: "Ear-Sy Rider", tags: [] },
        "2": { title: "Full Bars", tags: [] },
        "3": { title: "Bob Fires the Kids", tags: [] },
        "4": { title: "Mutiny on the Windbreaker", tags: [] },
        "5": { title: "An Indecent Thanksgiving Proposal", tags: [] },
        "6": { title: "The Deepening", tags: [] },
        "7": { title: "Tina-Rannosaurus Wrecks", tags: [] },
        "8": { title: "The Unbearable Like-Likeness of Gene", tags: [] },
        "9": { title: "Bob Rest Ye Merry Gentle-Mannequins", tags: [] },
        "10": { title: "Mother Daughter Laser Razor", tags: [] },
        "11": { title: "Nude Beach", tags: [] },
        "12": { title: "Broadcast Wagstaff School News", tags: [] },
        "13": { title: "My Fuzzy Valentine", tags: [] },
        "14": { title: "Lindapendent Woman", tags: [] },
        "15": { title: "O.T.: The Outside Toilet", tags: [] },
        "16": { title: "Topsy", tags: [] },
        "17": { title: "Two for Tina", tags: [] },
        "18": { title: "It Snakes a Village", tags: [] },
        "19": { title: "Family Fracas", tags: [] },
        "20": { title: "The Kids Run the Restaurant", tags: [] },
        "21": { title: "Boyz 4 Now", tags: [] },
        "22": { title: "Carpe Museum", tags: [] },
        "23": { title: "The Unnatural", tags: [] },
      },
      "4": {
        "1": { title: "A River Runs Through Bob", tags: [] },
        "2": { title: "Fort Night", tags: [] },
        "3": { title: "Seaplane!", tags: [] },
        "4": { title: "My Big Fat Greek Bob", tags: [] },
        "5": { title: "Turkey in a Can", tags: [] },
        "6": { title: "Purple Rain-Union", tags: [] },
        "7": { title: "Bob and Deliver", tags: [] },
        "8": { title: "Christmas in the Car", tags: [] },
        "9": { title: "Slumber Party", tags: [] },
        "10": { title: "Presto-Tina-o", tags: [] },
        "11": { title: "Easy Com-mercial, Easy Go-mercial", tags: [] },
        "12": { title: "The Frond Files", tags: [] },
        "13": { title: "Mazel Tina", tags: [] },
        "14": { title: "Uncle Teddy", tags: [] },
        "15": { title: "The Kids Rob a Train", tags: [] },
        "16": { title: "I Get Psychic Out of You", tags: [] },
        "17": { title: "The Equestranauts", tags: [] },
        "18": { title: "Ambergris", tags: [] },
        "19": { title: "The Kids Run Away", tags: [] },
        "20": { title: "Gene It On", tags: [] },
        "21": { title: "Wharf Horse (or How Bob Saves/Destroys the Town - Part I)", tags: [] },
        "22": { title: "World Wharf II: The Wharfening (or How Bob Saves/Destroys the Town - Part II)", tags: [] },
      },
      "5": {
        "1": { title: "Work Hard or Die Trying, Girl", tags: [] },
        "2": { title: "Tina and the Real Ghost", tags: [] },
        "3": { title: "Friends with Burger-fits", tags: [] },
        "4": { title: "Dawn of the Peck", tags: [] },
        "5": { title: "Best Burger", tags: [] },
        "6": { title: "Father of the Bob", tags: [] },
        "7": { title: "Tina Tailor Soldier Spy", tags: [] },
        "8": { title: "Midday Run", tags: [] },
        "9": { title: "Speakeasy Rider", tags: [] },
        "10": { title: "Late Afternoon in the Garden of Bob and Louise", tags: [] },
        "11": { title: "Can't Buy Me Math", tags: [] },
        "12": { title: "The Millie-churian Candiate", tags: [] },
        "13": { title: "The Gayle Tales", tags: [] },
        "14": { title: "L'il Hard Dad", tags: [] },
        "15": { title: "Adventures in Chinchilla-sitting", tags: [] },
        "16": { title: "The Runway Club", tags: [] },
        "17": { title: "Itty Bitty Ditty Committee", tags: [] },
        "18": { title: "Eat, Spray, Linda", tags: [] },
        "19": { title: "Housetrap", tags: [] },
        "20": { title: "Hawk & Chick", tags: [] },
        "21": { title: "The Oeder Games", tags: [] },
      },
      "6": {
        "1": { title: "Sliding Bobs", tags: [] },
        "2": { title: "The Land Ship", tags: [] },
        "3": { title: "The Hauntening", tags: [] },
        "4": { title: "Gayle Makin' Bob Sled", tags: [] },
        "5": { title: "Nice-Capades", tags: [] },
        "6": { title: "The Cook, the Steve, the Gayle, & Her Lover", tags: [] },
        "7": { title: "The Gene and Courtney Show", tags: [] },
        "8": { title: "Sexy Dance Healing", tags: [] },
        "9": { title: "Sacred Couch", tags: [] },
        "10": { title: "Lice Things Are Lice", tags: [] },
        "11": { title: "House of 1000 Bounces", tags: [] },
        "12": { title: "Stand by Gene", tags: [] },
        "13": { title: "Wag the Hog", tags: [] },
        "14": { title: "The Hormone-iums", tags: [] },
        "15": { title: "Pro Tiki/Con Tiki", tags: [] },
        "16": { title: "Bye Bye Boo Boo", tags: [] },
        "17": { title: "The Horse Rider-er", tags: [] },
        "18": { title: "Secret Admiral-irer", tags: [] },
        "19": { title: "Glued, Where's My Bob?", tags: [] },
      },
      "7": {
        "1": { title: "Flu-ouise", tags: [] },
        "2": { title: "Sea Me Now", tags: [] },
        "3": { title: "Teen-a-Witch", tags: [] },
        "4": { title: "They Serve Horses, Don't They?", tags: [] },
        "5": { title: "Larger Brother, Where Fart Thou?", tags: [] },
        "6": { title: "The Quirk-ducers", tags: [] },
        "7": { title: "The Last Gingerbread House on the Left", tags: [] },
        "8": { title: "Ex Mach Tina", tags: [] },
        "9": { title: "Bob Actually", tags: [] },
        "10": { title: "There's No Business Like Mr. Business Business", tags: [] },
        "11": { title: "A Few 'Gurt Men", tags: [] },
        "12": { title: "Like Gene for Chocolate", tags: [] },
        "13": { title: "The Grand Mama-Pest Hotel", tags: [] },
        "14": { title: "Aquaticism", tags: [] },
        "15": { title: "Ain't Miss Debatin'", tags: [] },
        "16": { title: "Eggs for Days", tags: [] },
        "17": { title: "Zero Larp Thirty", tags: [] },
        "18": { title: "The Laser-inth", tags: [] },
        "19": { title: "Thelma & Louise Except Thelma Is Linda", tags: [] },
        "20": { title: "Mom, Lies and Videotapes", tags: [] },
        "21": { title: "Paraders of the Lost Float", tags: [] },
        "22": { title: "Into the Mild", tags: [] },
      },
      "8": {
        "1": { title: "Brunchsquatch", tags: [] },
        "2": { title: "The Silence of the Louise", tags: [] },
        "3": { title: "The Wolf of Wharf Street", tags: [] },
        "4": { title: "Sit Me Baby One More Time", tags: [] },
        "5": { title: "Thanks-hoarding", tags: [] },
        "6": { title: "The Bleakening", tags: [] },
        "7": { title: "V for Valentine-detta", tags: [] },
        "8": { title: "Y Tu Ga-Ga Tambien", tags: [] },
        "9": { title: "The Secret Ceramics Room of Secrets", tags: [] },
        "10": { title: "Sleeping with the Frenemy", tags: [] },
        "11": { title: "The Hurt Soccer", tags: [] },
        "12": { title: "Cheer Up Sleepy Gene", tags: [] },
        "13": { title: "The Trouble with Doubles", tags: [] },
        "14": { title: "Go Tina on the Mountain", tags: [] },
        "15": { title: "Are You There Bob? It's Me, Birthday", tags: [] },
        "16": { title: "Boywatch", tags: [] },
        "17": { title: "As I Walk Through the Alley of the Shadow of Ramps", tags: [] },
        "18": { title: "Mo Mommy Mo Problems", tags: [] },
        "19": { title: "Mission Impos-Slug-Ble", tags: [] },
        "20": { title: "Something Old, Something New, Something Bob Caters for You", tags: [] },
      },
      "9": {
        "1": { title: "Just One of the Boyz 4 Now for Now", tags: [] },
        "2": { title: "The Taking of Funtime One Two Three", tags: [] },
        "3": { title: "Tweentrepreneurs", tags: [] },
        "4": { title: "Nightmare on Ocean Avenue Street", tags: [] },
        "5": { title: "Live and Let Fly", tags: [] },
        "6": { title: "Bobby Driver", tags: [] },
        "7": { title: "I Bob Your Pardon", tags: [] },
        "8": { title: "Roller? I Hardly Know Her!", tags: [] },
        "9": { title: "UFO No You Didn't", tags: [] },
        "10": { title: "Better Off Sled", tags: [] },
        "11": { title: "Lorenzo's Oil? No, Linda's", tags: [] },
        "12": { title: "The Helen Hunt", tags: [] },
        "13": { title: "Bed, Bob & Beyond", tags: [] },
        "14": { title: "Every Which Way But Goose", tags: [] },
        "15": { title: "The Fresh Princ-ipal", tags: [] },
        "16": { title: "Roamin' Bob-iday", tags: [] },
        "17": { title: "What About Blob?", tags: [] },
        "18": { title: "If You Love It So Much, Why Don't You Marionette?", tags: [] },
        "19": { title: "Long Time Listener, First Time Bob", tags: [] },
        "20": { title: "The Gene Mile", tags: [] },
        "21": { title: "P.T.A It Ain't So", tags: [] },
        "22": { title: "Yes Without My Zeke", tags: [] },
      },
      "10": {
        "1": { title: "The Ring (But Not Scary)", tags: [] },
        "2": { title: "Boys Just Wanna Have Fungus", tags: [] },
        "3": { title: "Motor, She Boat", tags: [] },
        "4": { title: "Pig Trouble in Little Tina", tags: [] },
        "5": { title: "Legends of the Mall", tags: [] },
        "6": { title: "The Hawkening: Look Who's Hawking Now", tags: [] },
        "7": { title: "Land of the Loft", tags: [] },
        "8": { title: "Now We're Not Cooking with Gas", tags: [] },
        "9": { title: "All That Gene", tags: [] },
        "10": { title: "Have Yourself a Maily Linda Christmas", tags: [] },
        "11": { title: "Drumforgiven", tags: [] },
        "12": { title: "A Fish Called Tina", tags: [] },
        "13": { title: "Three Girls and a Little Wharfy", tags: [] },
        "14": { title: "Wag the Song", tags: [] },
        "15": { title: "Flat-Top O' the Morning to Ya", tags: [] },
        "16": { title: "Yurty Rotten Scoundrels", tags: [] },
        "17": { title: "Just the Trip", tags: [] },
        "18": { title: "Tappy Tappy Tappy Tap Tap Tap", tags: [] },
        "19": { title: "The Handyman Can", tags: [] },
        "20": { title: "Poops!... I Didn't Do It Again", tags: [] },
        "21": { title: "Local She-ro", tags: [] },
        "22": { title: "Prank You for Being a Friend", tags: [] },
      },
      "11": {
        "1": { title: "Dream a Little Bob of Bob", tags: [] },
        "2": { title: "Worms of In-Rear-Ment", tags: [] },
        "3": { title: "Copa-Bob-Bana", tags: [] },
        "4": { title: "Heartbreak Hotel-oween", tags: [] },
        "5": { title: "Fast Time Capsules at Wagstaff School", tags: [] },
        "6": { title: "Bob Belcher and the Terrible, Horrible, No Good, Very Bad Kids", tags: [] },
        "7": { title: "Diarrhea of a Poopy Kid", tags: [] },
        "8": { title: "The Terminalator II: Terminals of Endearment", tags: [] },
        "9": { title: "Mommy Boy", tags: [] },
        "10": { title: "Yachty or Nice", tags: [] },
        "11": { title: "Romancing the Beef", tags: [] },
        "12": { title: "Die Card, or Card Trying", tags: [] },
        "13": { title: "An Incon-wheelie-ent Truth", tags: [] },
        "14": { title: "Mr. Lonely Farts", tags: [] },
        "15": { title: "Sheshank Redumption", tags: [] },
        "16": { title: "Y Tu Tina También", tags: [] },
        "17": { title: "Fingers-Loose", tags: [] },
        "18": { title: "Some Kind of Fender Benderful", tags: [] },
        "19": { title: "Bridge Over Troubled Rudy", tags: [] },
        "20": { title: "Steal Magazine-olias", tags: [] },
        "21": { title: "Tell Me Dumb Thing Good", tags: [] },
        "22": { title: "Vampire Disco Death Dance", tags: [] },
      },
      "12": {
        "1": { title: "Manic Pixie Crap Show", tags: [] },
        "2": { title: "Crystal Mess", tags: [] },
        "3": { title: "The Pumpkinening", tags: [] },
        "4": { title: "Driving Big Dummy", tags: [] },
        "5": { title: "Seven-tween Again", tags: [] },
        "6": { title: "Beach, Please", tags: [] },
        "7": { title: "Loft in Bedslation", tags: [] },
        "8": { title: "Stuck in the Kitchen with You", tags: [] },
        "9": { title: "FOMO You Didn't", tags: [] },
        "10": { title: "Gene's Christmas Break", tags: [] },
        "11": { title: "Touch of Eval(uations)", tags: [] },
        "12": { title: "Ferry on My Wayward Bob and Linda", tags: [] },
        "13": { title: "Frigate Me Knot", tags: [] },
        "14": { title: "Video Killed the Gene-io Star", tags: [] },
        "15": { title: "Ancient Misbehavin", tags: [] },
        "16": { title: "Interview with a Pop-pop-pire", tags: [] },
        "17": { title: "The Spider House Rules", tags: [] },
        "18": { title: "Clear and Present Ginger", tags: [] },
        "19": { title: "A-Sprout a Boy", tags: [] },
        "20": { title: "Sauce Side Story", tags: [] },
        "21": { title: "Some Like It Bot Part 1: Eighth Grade Runner", tags: [] },
        "22": { title: "Some Like It Bot Part 2: Judge-bot Day", tags: [] },
      },
      "13": {
        "1": { title: "To Bob, or Not to Bob", tags: [] },
        "2": { title: "The Reeky Lake Show", tags: [] },
        "3": { title: "What About Job?", tags: [] },
        "4": { title: "Comet-y of Errors", tags: [] },
        "5": { title: "So You Stink You Can Dance", tags: [] },
        "6": { title: "Apple Gore-chard! (But Not Gory)", tags: [] },
        "7": { title: "Ready Player Gene", tags: [] },
        "8": { title: "Putts-giving", tags: [] },
        "9": { title: "Show Mama from the Grave", tags: [] },
        "10": { title: "The Plight Before Christmas", tags: [] },
        "11": { title: "Cheaty Cheaty Bang Bang", tags: [] },
        "12": { title: "Oh Row You Didn't", tags: [] },
        "13": { title: "Stop! Or My Mom Will Sleuth!", tags: [] },
        "14": { title: "These Boots Are Made for Stalking", tags: [] },
        "15": { title: "The Show (And Tell) Must Go On", tags: [] },
        "16": { title: "What a (April) Fool Believes", tags: [] },
        "17": { title: "Crows Encounters of the Bird Kind", tags: [] },
        "18": { title: "Gift Card or Buy Trying", tags: [] },
        "19": { title: "Crab-solutely Fabulous", tags: [] },
        "20": { title: "Radio No You Didn't", tags: [] },
        "21": { title: "Mother Author Laser Pointer", tags: [] },
        "22": { title: "Amelia", tags: [] },
      },
      "14": {
        "1": { title: "Fight at the Not Okay Chore-ral", tags: [] },
        "2": { title: "The Amazing Rudy", tags: [] },
        "3": { title: "The Pickleorette", tags: [] },
        "4": { title: "Running Down a Gene", tags: [] },
        "5": { title: "Bully-ieve It or Not", tags: [] },
        "6": { title: "Escape from Which Island?", tags: [] },
        "7": { title: "The (Raccoon) King and I", tags: [] },
        "8": { title: "Wharf, Me Worry?", tags: [] },
        "9": { title: "Fraud of the Dead: Zombie-Docu-Pocalypse", tags: [] },
        "10": { title: "The Nightmare 2 Days Before Christmas", tags: [] },
        "11": { title: "Mission Impossi-Bob", tags: [] },
        "12": { title: "Jade in the Shade", tags: [] },
        "13": { title: "Butt Sweat and Fears", tags: [] },
        "14": { title: "The Big Stieblitzki", tags: [] },
        "15": { title: "The Right Tough Stuff", tags: [] },
        "16": { title: "To Catch a Beef", tags: [] },
      },
      "15": {
        "1": { title: "The Tina Table: The Tables Have Tina-ed", tags: [] },
        "2": { title: "Saving Favorite Drive-In", tags: [] },
        "3": { title: "Colon-ly the Dronely", tags: [] },
        "4": { title: "For Whom the Doll Toes", tags: [] },
        "5": { title: "Don't Stop Be-Cheesin", tags: [] },
        "6": { title: "Hope N' Mic Night", tags: [] },
        "7": { title: "Boogie Days", tags: [] },
        "8": { title: "They Slug Horses, Don't They?", tags: [] },
        "9": { title: "Dog Christmas Day After Afternoon", tags: [] },
        "10": { title: "Advice Things Are Ad-nice", tags: [] },
      },
    }
    },
    "Brooklyn Nine-Nine": {
    seasons: {
      "1": {
        "1": { title: "Pilot", tags: [] },
        "2": { title: "The Tagger", tags: [] },
        "3": { title: "The Slump", tags: [] },
        "4": { title: "M.E. Time", tags: [] },
        "5": { title: "The Vulture", tags: [] },
        "6": { title: "Halloween", tags: [] },
        "7": { title: "48 Hours", tags: [] },
        "8": { title: "Old School", tags: [] },
        "9": { title: "Sal's Pizza", tags: [] },
        "10": { title: "Thanksgiving", tags: [] },
        "11": { title: "Christmas", tags: [] },
        "12": { title: "Pontiac Bandit", tags: [] },
        "13": { title: "The Bet", tags: [] },
        "14": { title: "The Ebony Falcon", tags: [] },
        "15": { title: "Operation: Broken Feather", tags: [] },
        "16": { title: "The Party", tags: [] },
        "17": { title: "Full Boyle", tags: [] },
        "18": { title: "The Apartment", tags: [] },
        "19": { title: "Tactical Village", tags: [] },
        "20": { title: "Fancy Brudgom", tags: [] },
        "21": { title: "Unsolvable", tags: [] },
        "22": { title: "Charges and Specs", tags: [] },
      },
      "2": {
        "1": { title: "Undercover", tags: [] },
        "2": { title: "Chocolate Milk", tags: [] },
        "3": { title: "The Jimmy Jab Games", tags: [] },
        "4": { title: "Halloween II", tags: [] },
        "5": { title: "The Mole", tags: [] },
        "6": { title: "Jake and Sophia", tags: [] },
        "7": { title: "Lockdown", tags: [] },
        "8": { title: "USPIS", tags: [] },
        "9": { title: "The Road Trip", tags: [] },
        "10": { title: "The Pontiac Bandit Returns", tags: [] },
        "11": { title: "Stakeout", tags: [] },
        "12": { title: "Beach House", tags: [] },
        "13": { title: "Payback", tags: [] },
        "14": { title: "Defense Rests", tags: [] },
        "15": { title: "Windbreaker City", tags: [] },
        "16": { title: "The Wednesday Incident", tags: [] },
        "17": { title: "Boyle-Linetti Wedding", tags: [] },
        "18": { title: "Captain Peralta", tags: [] },
        "19": { title: "Sabotage", tags: [] },
        "20": { title: "AC/DC", tags: [] },
        "21": { title: "Det. Dave Majors", tags: [] },
        "22": { title: "The Chopper", tags: [] },
        "23": { title: "Johnny and Dora", tags: [] },
      },
      "3": {
        "1": { title: "New Captain", tags: [] },
        "2": { title: "The Funeral", tags: [] },
        "3": { title: "Boyle's Hunch", tags: [] },
        "4": { title: "The Oolong Slayer", tags: [] },
        "5": { title: "Halloween III", tags: [] },
        "6": { title: "Into the Woods", tags: [] },
        "7": { title: "The Mattress", tags: [] },
        "8": { title: "Ava", tags: [] },
        "9": { title: "The Swedes", tags: [] },
        "10": { title: "Yippie Kayak", tags: [] },
        "11": { title: "Hostage Situation", tags: [] },
        "12": { title: "9 Days", tags: [] },
        "13": { title: "The Cruise", tags: [] },
        "14": { title: "Karen Peralta", tags: [] },
        "15": { title: "The 9-8", tags: [] },
        "16": { title: "House Mouses", tags: [] },
        "17": { title: "Adrian Pimento", tags: [] },
        "18": { title: "Cheddar", tags: [] },
        "19": { title: "Terry Kitties", tags: [] },
        "20": { title: "Paranoia", tags: [] },
        "21": { title: "Maximum Security", tags: [] },
        "22": { title: "Bureau", tags: [] },
        "23": { title: "Greg and Larry", tags: [] },
      },
      "4": {
        "1": { title: "Coral Palms, Part 1", tags: [] },
        "2": { title: "Coral Palms, Part 2", tags: [] },
        "3": { title: "Coral Palms, Part 3", tags: [] },
        "4": { title: "The Night Shift", tags: [] },
        "5": { title: "Halloween IV", tags: [] },
        "6": { title: "Monster in the Closet", tags: [] },
        "7": { title: "Mr. Santiago", tags: [] },
        "8": { title: "Skyfire Cycle", tags: [] },
        "9": { title: "The Overmining", tags: [] },
        "10": { title: "Captain Latvia", tags: [] },
        "11": { title: "The Fugitive, Part 1", tags: [] },
        "12": { title: "The Fugitive, Part 2", tags: [] },
        "13": { title: "The Audit", tags: [] },
        "14": { title: "Serve & Protect", tags: [] },
        "15": { title: "The Last Ride", tags: [] },
        "16": { title: "Moo Moo", tags: [] },
        "17": { title: "Cop-Con", tags: [] },
        "18": { title: "Chasing Amy", tags: [] },
        "19": { title: "Your Honor", tags: [] },
        "20": { title: "The Slaughterhouse", tags: [] },
        "21": { title: "The Bank Job", tags: [] },
        "22": { title: "Crime & Punishment", tags: [] },
      },
      "5": {
        "1": { title: "The Big House Pt. 1", tags: [] },
        "2": { title: "The Big House Pt. 2", tags: [] },
        "3": { title: "Kicks", tags: [] },
        "4": { title: "HalloVeen", tags: [] },
        "5": { title: "Bad Beat", tags: [] },
        "6": { title: "The Venue", tags: [] },
        "7": { title: "Two Turkeys", tags: [] },
        "8": { title: "Return to Skyfire", tags: [] },
        "9": { title: "99", tags: [] },
        "10": { title: "Game Night", tags: [] },
        "11": { title: "The Favor", tags: [] },
        "12": { title: "Safe House", tags: [] },
        "13": { title: "The Negotiation", tags: [] },
        "14": { title: "The Box", tags: [] },
        "15": { title: "The Puzzle Master", tags: [] },
        "16": { title: "NutriBoom", tags: [] },
        "17": { title: "DFW", tags: [] },
        "18": { title: "Gray Star Mutual", tags: [] },
        "19": { title: "Bachelor/ette Party", tags: [] },
        "20": { title: "Show Me Going", tags: [] },
        "21": { title: "White Whale", tags: [] },
        "22": { title: "Jake & Amy", tags: [] },
      },
      "6": {
        "1": { title: "Honeymoon", tags: [] },
        "2": { title: "Hitchcock & Scully", tags: [] },
        "3": { title: "The Tattler", tags: [] },
        "4": { title: "Four Movements", tags: [] },
        "5": { title: "A Tale of Two Bandits", tags: [] },
        "6": { title: "The Crime Scene", tags: [] },
        "7": { title: "The Honeypot", tags: [] },
        "8": { title: "He Said, She Said", tags: [] },
        "9": { title: "The Golden Child", tags: [] },
        "10": { title: "Gintars", tags: [] },
        "11": { title: "The Therapist", tags: [] },
        "12": { title: "Casecation", tags: [] },
        "13": { title: "The Bimbo", tags: [] },
        "14": { title: "Ticking Clocks", tags: [] },
        "15": { title: "Return of the King", tags: [] },
        "16": { title: "Cinco de Mayo", tags: [] },
        "17": { title: "Sicko", tags: [] },
        "18": { title: "Suicide Squad", tags: [] },
      },
      "7": {
        "1": { title: "Manhunter", tags: [] },
        "2": { title: "Captain Kim", tags: [] },
        "3": { title: "Pimemento", tags: [] },
        "4": { title: "The Jimmy Jab Games II", tags: [] },
        "5": { title: "Debbie", tags: [] },
        "6": { title: "Trying", tags: [] },
        "7": { title: "Ding Dong", tags: [] },
        "8": { title: "The Takeback", tags: [] },
        "9": { title: "Dillman", tags: [] },
        "10": { title: "Admiral Peralta", tags: [] },
        "11": { title: "Valloweaster", tags: [] },
        "12": { title: "Ransom", tags: [] },
        "13": { title: "Lights Out", tags: [] },
      },
      "8": {
        "1": { title: "The Good Ones", tags: [] },
        "2": { title: "The Lake House", tags: [] },
        "3": { title: "Blue Flu", tags: [] },
        "4": { title: "Balancing", tags: [] },
        "5": { title: "PB&J", tags: [] },
        "6": { title: "The Set Up", tags: [] },
        "7": { title: "Game of Boyles", tags: [] },
        "8": { title: "Renewal", tags: [] },
        "9": { title: "The Last Day Pt 1", tags: [] },
        "10": { title: "The Last Day Pt 2", tags: [] },
      },
    }
    },
    "Letterkenny": {
    seasons: {
      "1": {
        "1": { title: "Ain't No Reason to Get Excited", tags: [] },
        "2": { title: "Super Soft Birthday", tags: [] },
        "3": { title: "Fartbook", tags: [] },
        "4": { title: "Wingman Wayne", tags: [] },
        "5": { title: "Rave", tags: [] },
        "6": { title: "A Fuss in the Back Bush", tags: [] },
      },
      "2": {
        "1": { title: "A Fuss at the AG Hall", tags: [] },
        "2": { title: "The Election", tags: [] },
        "3": { title: "Relationships", tags: [] },
        "4": { title: "The Native Flu", tags: [] },
        "5": { title: "Uncle Eddie's Trust", tags: [] },
        "6": { title: "Finding Stormy a Stud", tags: [] },
        "7": { title: "St. Perfect's Day", tags: [] },
      },
      "3": {
        "1": { title: "Sled Shack", tags: [] },
        "2": { title: "Puck Bunny", tags: [] },
        "3": { title: "MoDeans 2", tags: [] },
        "4": { title: "Les Hiques", tags: [] },
        "5": { title: "The Battle for Bonnie McMurray", tags: [] },
        "6": { title: "Bradley Is a Killer", tags: [] },
        "7": { title: "The Haunting of MoDean's II", tags: [] },
      },
      "4": {
        "1": { title: "Never Work a Day in Your Life", tags: [] },
        "2": { title: "A Fuss at the Golf Course", tags: [] },
        "3": { title: "Way to a Man's Heart", tags: [] },
        "4": { title: "Letterkenny Talent Show", tags: [] },
        "5": { title: "The Letterkenny Leave", tags: [] },
        "6": { title: "Great Day for Thunder Bay", tags: [] },
        "7": { title: "Super Hard Easter", tags: [] },
      },
      "5": {
        "1": { title: "We Don't Fight at Weddings", tags: [] },
        "2": { title: "The Ol' College Try", tags: [] },
        "3": { title: "Hard Right Jay", tags: [] },
        "4": { title: "Letterkenny Spelling Bee", tags: [] },
        "5": { title: "Back to Back to Back", tags: [] },
        "6": { title: "Bock et Biche", tags: [] },
      },
      "6": {
        "0": { title: "The Three Wise Men", tags: [] },
        "1": { title: "What Could Be So Urgent?", tags: [] },
        "2": { title: "Bush Party Season", tags: [] },
        "3": { title: "The City", tags: [] },
        "4": { title: "Dyck's Slip Out", tags: [] },
        "5": { title: "Different Strokes For Different Folks", tags: [] },
        "6": { title: "Yew!", tags: [] },
        "7": { title: "Valentime's Day", tags: [] },
      },
      "7": {
        "1": { title: "Crack An Ag", tags: [] },
        "2": { title: "Red Card Yellow Card", tags: [] },
        "3": { title: "Nut", tags: [] },
        "4": { title: "Letterkenny vs Penny", tags: [] },
        "5": { title: "W's Talk, Baby", tags: [] },
        "6": { title: "In It to Win It", tags: [] },
      },
      "8": {
        "1": { title: "Miss Fire", tags: [] },
        "2": { title: "National Senior Hockey Championship", tags: [] },
        "3": { title: "The Rippers", tags: [] },
        "4": { title: "Ferda", tags: [] },
        "5": { title: "Yard Sale Saturday", tags: [] },
        "6": { title: "Holy Sheet", tags: [] },
        "7": { title: "Day Beers Day", tags: [] },
      },
      "9": {
        "1": { title: "American Buck and Doe", tags: [] },
        "2": { title: "Kids with Problems", tags: [] },
        "3": { title: "Scorched Earth", tags: [] },
        "4": { title: "Mitzvah", tags: [] },
        "5": { title: "Sleepover", tags: [] },
        "6": { title: "Breastaurant", tags: [] },
        "7": { title: "NDN NRG", tags: [] },
      },
      "10": {
        "1": { title: "King of Suckers", tags: [] },
        "2": { title: "Dealership", tags: [] },
        "3": { title: "Dyck Meat", tags: [] },
        "4": { title: "Prostate", tags: [] },
        "5": { title: "VidVok", tags: [] },
        "6": { title: "Sundays are for Picking Stones", tags: [] },
        "7": { title: "Special", tags: [] },
      },
      "11": {
        "1": { title: "Chips", tags: [] },
        "2": { title: "Okoya", tags: [] },
        "3": { title: "Lost Dog", tags: [] },
        "4": { title: "Nudes", tags: [] },
        "5": { title: "Influenzas", tags: [] },
        "6": { title: "Degens", tags: [] },
        "7": { title: "May 2-4", tags: [] },
      },
      "12": {
        "1": { title: "Live at MoDean's", tags: [] },
        "2": { title: "Sun Darts", tags: [] },
        "3": { title: "I'm a Degen", tags: [] },
        "4": { title: "Snooters", tags: [] },
        "5": { title: "Stuck", tags: [] },
        "6": { title: "Over and Out", tags: [] },
      },
    }
    },
    "30 Rock": {
    seasons: {
      "1": {
        "1": { title: "Pilot", tags: [] },
        "2": { title: "The Aftermath", tags: [] },
        "3": { title: "Blind Date", tags: [] },
        "4": { title: "Jack the Writer", tags: [] },
        "5": { title: "Jack-Tor", tags: [] },
        "6": { title: "Jack Meets Dennis", tags: [] },
        "7": { title: "Tracy Does Conan", tags: [] },
        "8": { title: "The Break-Up", tags: [] },
        "9": { title: "The Baby Show", tags: [] },
        "10": { title: "The Rural Juror", tags: [] },
        "11": { title: "The Head and the Hair", tags: [] },
        "12": { title: "Black Tie", tags: [] },
        "13": { title: "Up All Night", tags: [] },
        "14": { title: "The C Word", tags: [] },
        "15": { title: "Hard Ball", tags: [] },
        "16": { title: "The Source Awards", tags: [] },
        "17": { title: "The Fighting Irish", tags: [] },
        "18": { title: "Fireworks", tags: [] },
        "19": { title: "Corporate Crush", tags: [] },
        "20": { title: "Cleveland", tags: [] },
        "21": { title: "Hiatus", tags: [] },
      },
      "2": {
        "1": { title: "SeinfeldVision", tags: [] },
        "2": { title: "Jack Gets in the Game", tags: [] },
        "3": { title: "The Collection", tags: [] },
        "4": { title: "Rosemary's Baby", tags: [] },
        "5": { title: "Greenzo", tags: [] },
        "6": { title: "Somebody to Love", tags: [] },
        "7": { title: "Cougars", tags: [] },
        "8": { title: "Secrets and Lies", tags: [] },
        "9": { title: "Ludachristmas", tags: [] },
        "10": { title: "Episode 210", tags: [] },
        "11": { title: "MILF Island", tags: [] },
        "12": { title: "Subway Hero", tags: [] },
        "13": { title: "Succession", tags: [] },
        "14": { title: "Sandwich Day", tags: [] },
        "15": { title: "Cooter", tags: [] },
      },
      "3": {
        "1": { title: "Do-Over", tags: [] },
        "2": { title: "Believe in the Stars", tags: [] },
        "3": { title: "The One with the Cast of 'Night Court'", tags: [] },
        "4": { title: "Gavin Volure", tags: [] },
        "5": { title: "Reunion", tags: [] },
        "6": { title: "Christmas Special", tags: [] },
        "7": { title: "Señor Macho Solo", tags: [] },
        "8": { title: "Flu Shot", tags: [] },
        "9": { title: "Retreat to Move Forward", tags: [] },
        "10": { title: "Generalissimo", tags: [] },
        "11": { title: "St. Valentine's Day", tags: [] },
        "12": { title: "Larry King", tags: [] },
        "13": { title: "Goodbye, My Friend", tags: [] },
        "14": { title: "The Funcooker", tags: [] },
        "15": { title: "The Bubble", tags: [] },
        "16": { title: "Apollo, Apollo", tags: [] },
        "17": { title: "Cutbacks", tags: [] },
        "18": { title: "Jackie Jormp-Jomp", tags: [] },
        "19": { title: "The Ones", tags: [] },
        "20": { title: "The Natural Order", tags: [] },
        "21": { title: "Mamma Mia", tags: [] },
        "22": { title: "Kidney Now!", tags: [] },
      },
      "4": {
        "1": { title: "Season 4", tags: [] },
        "2": { title: "Into the Crevasse", tags: [] },
        "3": { title: "Stone Mountain", tags: [] },
        "4": { title: "Audition Day", tags: [] },
        "5": { title: "The Problem Solvers", tags: [] },
        "6": { title: "Sun Tea", tags: [] },
        "7": { title: "Dealbreakers Talk Show #0001", tags: [] },
        "8": { title: "Secret Santa", tags: [] },
        "9": { title: "Klaus and Greta", tags: [] },
        "10": { title: "Black Light Attack!", tags: [] },
        "11": { title: "Winter Madness", tags: [] },
        "12": { title: "Verna", tags: [] },
        "13": { title: "Anna Howard Shaw Day", tags: [] },
        "14": { title: "Future Husband", tags: [] },
        "15": { title: "Don Geiss, America and Hope", tags: [] },
        "16": { title: "Floyd", tags: [] },
        "17": { title: "Lee Marvin vs. Derek Jeter", tags: [] },
        "18": { title: "Khonani", tags: [] },
        "19": { title: "Argus", tags: [] },
        "20": { title: "The Moms", tags: [] },
        "21": { title: "Emmanuelle Goes to Dinosaur Land", tags: [] },
        "22": { title: "I Do Do", tags: [] },
      },
      "5": {
        "1": { title: "The Fabian Strategy", tags: [] },
        "2": { title: "When It Rains, It Pours", tags: [] },
        "3": { title: "Let's Stay Together", tags: [] },
        "4": { title: "Live Show", tags: [] },
        "5": { title: "Reaganing", tags: [] },
        "6": { title: "Gentleman's Intermission", tags: [] },
        "7": { title: "Brooklyn Without Limits", tags: [] },
        "8": { title: "College", tags: [] },
        "9": { title: "Chain Reaction of Mental Anguish", tags: [] },
        "10": { title: "Christmas Attack Zone", tags: [] },
        "11": { title: "Mrs. Donaghy", tags: [] },
        "12": { title: "Operation Righteous Cowboy Lightning", tags: [] },
        "13": { title: "¡Qué Sorpresa!", tags: [] },
        "14": { title: "Double-Edged Sword", tags: [] },
        "15": { title: "It's Never Too Late for Now", tags: [] },
        "16": { title: "TGS Hates Women", tags: [] },
        "17": { title: "Queen of Jordan", tags: [] },
        "18": { title: "Plan B", tags: [] },
        "19": { title: "I Heart Connecticut", tags: [] },
        "20": { title: "100: Part 1", tags: [] },
        "21": { title: "100: Part 2", tags: [] },
        "22": { title: "Everything Sunny All the Time Always", tags: [] },
        "23": { title: "Respawn", tags: [] },
      },
      "6": {
        "1": { title: "Dance Like Nobody's Watching", tags: [] },
        "2": { title: "Idiots Are People Two!", tags: [] },
        "3": { title: "Idiots Are People Three!", tags: [] },
        "4": { title: "The Ballad of Kenneth Parcell", tags: [] },
        "5": { title: "Today You Are a Man", tags: [] },
        "6": { title: "Hey, Baby, What's Wrong?: Part 1", tags: [] },
        "7": { title: "Hey, Baby, What's Wrong?: Part 2", tags: [] },
        "8": { title: "The Tuxedo Begins", tags: [] },
        "9": { title: "Leap Day", tags: [] },
        "10": { title: "Alexis Goodlooking and the Case of the Missing Whisky", tags: [] },
        "11": { title: "Standards and Practices", tags: [] },
        "12": { title: "St. Patrick's Day", tags: [] },
        "13": { title: "Grandmentor", tags: [] },
        "14": { title: "Kidnapped by Danger", tags: [] },
        "15": { title: "The Shower Principle", tags: [] },
        "16": { title: "Nothing Left to Lose", tags: [] },
        "17": { title: "Meet the Woggels!", tags: [] },
        "18": { title: "Murphy Brown Lied to Us", tags: [] },
        "19": { title: "Live from Studio 6H", tags: [] },
        "20": { title: "Queen of Jordan 2: The Mystery of the Phantom Pooper", tags: [] },
        "21": { title: "The Return of Avery Jessup", tags: [] },
        "22": { title: "What Will Happen to the Gang Next Year?", tags: [] },
      },
      "7": {
        "1": { title: "The Beginning of the End", tags: [] },
        "2": { title: "Governor Dunston", tags: [] },
        "3": { title: "Stride of Pride", tags: [] },
        "4": { title: "Unwindulax", tags: [] },
        "5": { title: "There's No I in America", tags: [] },
        "6": { title: "Aunt Phatso vs. Jack Donaghy", tags: [] },
        "7": { title: "Mazel Tov, Dummies!", tags: [] },
        "8": { title: "My Whole Life Is Thunder", tags: [] },
        "9": { title: "Game Over", tags: [] },
        "10": { title: "Florida", tags: [] },
        "11": { title: "A Goon's Deed in a Weary World", tags: [] },
        "12": { title: "Hogcock!/Last Lunch", tags: [] },
        "13": { title: "Last Lunch", tags: [] },
      },
    }
    },
    "Parks and Recreation": {
      seasons: {}
    },
    "King of the Hill": {
      seasons: {}
    },
    "The League": {
      seasons: {}
    },
    "It's Always Sunny in Philidephia": {
      seasons: {}
    },
    "Archer": {
      seasons: {}
    },
    "Rick & Morty": {
      seasons: {}
    },
    "Better Off Ted": {
      seasons: {}
    },
    "Raising Hope": {
      seasons: {}
    },
    "Drunk History": {
      seasons: {}
    },
    "Stan Against Evil": {
      seasons: {}
    },
    "The Great North": {
      seasons: {}
    },
    "New Girl": {
      seasons: {
        "1": {
          "1": { title: "Pilot", tags: [] },
          "2": { title: "Kryptonite", tags: [] },
          "3": { title: "Wedding", tags: [] },
          "4": { title: "Naked", tags: [] },
          "5": { title: "Cece Crashes", tags: [] },
          "6": { title: "Thanksgiving", tags: [] },
          "7": { title: "Bells", tags: [] },
          "8": { title: "Bad in Bed", tags: [] },
          "9": { title: "The 23rd", tags: [] },
          "10": { title: "The Story of the 50", tags: [] },
          "11": { title: "Jess & Julia", tags: [] },
          "12": { title: "The Landlord", tags: [] },
          "13": { title: "Valentine's Day", tags: [] },
          "14": { title: "Bully", tags: [] },
          "15": { title: "Injured", tags: [] },
          "16": { title: "Control", tags: [] },
          "17": { title: "Fancyman Part 1", tags: [] },
          "18": { title: "Fancyman Part 2", tags: [] },
          "19": { title: "Secrets", tags: [] },
          "20": { title: "Normal", tags: [] },
          "21": { title: "Kids", tags: [] },
          "22": { title: "Tomatoes", tags: [] },
          "23": { title: "Backslide", tags: [] },
          "24": { title: "See Ya", tags: [] },
        },
        "2": {
          "1": { title: "Re-launch", tags: [] },
          "2": { title: "Katie", tags: [] },
          "3": { title: "Fluffer", tags: [] },
          "4": { title: "Neighbors", tags: [] },
          "5": { title: "Models", tags: [] },
          "6": { title: "Halloween", tags: [] },
          "7": { title: "Menzies", tags: [] },
          "8": { title: "Parents", tags: [] },
          "9": { title: "Eggs", tags: [] },
          "10": { title: "Bathtub", tags: [] },
          "11": { title: "Santa", tags: [] },
          "12": { title: "Cabin", tags: [] },
          "13": { title: "A Father's Love", tags: [] },
          "14": { title: "Pepperwood", tags: [] },
          "15": { title: "Cooler", tags: [] },
          "16": { title: "Table 34", tags: [] },
          "17": { title: "Parking Spot", tags: [] },
          "18": { title: "Tinfinity", tags: [] },
          "19": { title: "Quick Hardening Caulk", tags: [] },
          "20": { title: "Chicago", tags: [] },
          "21": { title: "First Date", tags: [] },
          "22": { title: "Bachelorette Party", tags: [] },
          "23": { title: "Virgins", tags: [] },
          "24": { title: "Winston's Birthday", tags: [] },
          "25": { title: "Elaine's Big Day", tags: [] },
        },
        "3": {
          "1": { title: "All In", tags: [] },
          "2": { title: "Nerd", tags: [] },
          "3": { title: "Double Date", tags: [] },
          "4": { title: "The Captain", tags: [] },
          "5": { title: "The Box", tags: [] },
          "6": { title: "Keaton", tags: [] },
          "7": { title: "Coach", tags: [] },
          "8": { title: "Menus", tags: [] },
          "9": { title: "Longest Night Ever", tags: [] },
          "10": { title: "Thanksgiving III", tags: [] },
          "11": { title: "Clavado En Un Bar", tags: [] },
          "12": { title: "Basketsball", tags: [] },
          "13": { title: "Birthday", tags: [] },
          "14": { title: "Prince", tags: [] },
          "15": { title: "Exes", tags: [] },
          "16": { title: "Sister", tags: [] },
          "17": { title: "Sister II", tags: [] },
          "18": { title: "Sister III", tags: [] },
          "19": { title: "Fired Up", tags: [] },
          "20": { title: "Mars Landing", tags: [] },
          "21": { title: "Big News", tags: [] },
          "22": { title: "Dance", tags: [] },
          "23": { title: "Cruise", tags: [] },
        },
        "4": {
          "1": { title: "The Last Wedding", tags: [] },
          "2": { title: "Dice", tags: [] },
          "3": { title: "Julie Berkman's Older Sister", tags: [] },
          "4": { title: "Micro", tags: [] },
          "5": { title: "Landline", tags: [] },
          "6": { title: "Background Check", tags: [] },
          "7": { title: "Goldmine", tags: [] },
          "8": { title: "Teachers", tags: [] },
          "9": { title: "Thanksgiving IV", tags: [] },
          "10": { title: "Girl Fight", tags: [] },
          "11": { title: "LAXmas", tags: [] },
          "12": { title: "Shark", tags: [] },
          "13": { title: "Coming Out", tags: [] },
          "14": { title: "Swuit", tags: [] },
          "15": { title: "The Crawl", tags: [] },
          "16": { title: "Oregon", tags: [] },
          "17": { title: "Spiderhunt", tags: [] },
          "18": { title: "Walk of Shame", tags: [] },
          "19": { title: "The Right Thing", tags: [] },
          "20": { title: "Par 5", tags: [] },
          "21": { title: "Panty Gate", tags: [] },
          "22": { title: "Clean Break", tags: [] },
        },
        "5": {
          "1": { title: "Big Mama P", tags: [] },
          "2": { title: "What About Fred", tags: [] },
          "3": { title: "Jury Duty", tags: [] },
          "4": { title: "No Girl", tags: [] },
          "5": { title: "Bob & Carol & Nick & Schmidt", tags: [] },
          "6": { title: "Reagan", tags: [] },
          "7": { title: "Wig", tags: [] },
          "8": { title: "The Decision", tags: [] },
          "9": { title: "Heat Wave", tags: [] },
          "10": { title: "Goosebumps Walkaway", tags: [] },
          "11": { title: "The Apartment", tags: [] },
          "12": { title: "D-Day", tags: [] },
          "13": { title: "Sam, Again", tags: [] },
          "14": { title: "300 Feet", tags: [] },
          "15": { title: "Jeff Day", tags: [] },
          "16": { title: "Helmet", tags: [] },
          "17": { title: "Road Trip", tags: [] },
          "18": { title: "A Chill Day In", tags: [] },
          "19": { title: "Dress", tags: [] },
          "20": { title: "Return to Sender", tags: [] },
          "21": { title: "Wedding Eve", tags: [] },
          "22": { title: "Landing Gear", tags: [] },
        },
        "6": {
          "1": { title: "House Hunt", tags: [] },
          "2": { title: "Hubbedy Bubby", tags: [] },
          "3": { title: "Single and Sufficient", tags: [] },
          "4": { title: "Homecoming", tags: [] },
          "5": { title: "Jaipur Aviv", tags: [] },
          "6": { title: "Ready", tags: [] },
          "7": { title: "Last Thanksgiving", tags: [] },
          "8": { title: "James Wonder", tags: [] },
          "9": { title: "Es Good", tags: [] },
          "10": { title: "Christmas Eve Eve", tags: [] },
          "11": { title: "Raisin's Back", tags: [] },
          "12": { title: "The Cubicle", tags: [] },
          "13": { title: "Cece's Boys", tags: [] },
          "14": { title: "The Hike", tags: [] },
          "15": { title: "Glue", tags: [] },
          "16": { title: "Operation: Bobcat", tags: [] },
          "17": { title: "Rumspringa", tags: [] },
          "18": { title: "Young Adult", tags: [] },
          "19": { title: "Socalyalcon VI", tags: [] },
          "20": { title: "Misery", tags: [] },
          "21": { title: "San Diego", tags: [] },
          "22": { title: "Five Stars for Beezus", tags: [] },
        },
        "7": {
          "1": { title: "About Three Years Later", tags: [] },
          "2": { title: "Tuesday Meeting", tags: [] },
          "3": { title: "Lillypads", tags: [] },
          "4": { title: "Where the Road Goes", tags: [] },
          "5": { title: "Godparents", tags: [] },
          "6": { title: "Mario", tags: [] },
          "7": { title: "The Curse of the Pirate Bride", tags: [] },
          "8": { title: "Engram Pattersky", tags: [] },
        },
      }
    },
  };
}
